options:
  snap_channel:
    default: "stable"
    type: string
    description: |
        If install_method is set to "snap" this option controlls channel name.
        Supported values are: "stable", "candidate", "beta" and "edge"
  modules:
    default: |
      http_2xx:
        prober: http
        timeout: 10s
      tcp_connect:
        prober: tcp
        timeout: 10s
      icmp:
        prober: icmp
        timeout: 10s
        icmp:
          preferred_ip_protocol: "ip4"
    type: string
    description: |
        Blackbox exporter configuratin in raw YAML format
  scrape-interval:
    type: string
    default: "60s"
    description: Set the blackbox exporter scrape jobs custom interval.
